package com.westee.cake.generate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Config implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.ID
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.BUSINESS_START_TIME
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private Date businessStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.BUSINESS_END_TIME
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private Date businessEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private BigDecimal freeExpressAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.STORE_CLOSE_START
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private Date storeCloseStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.STORE_CLOSE_END
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private Date storeCloseEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.CREATED_AT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONFIG.UPDATED_AT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CONFIG
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIG
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Config(Integer id, Date businessStartTime, Date businessEndTime, BigDecimal freeExpressAmount, Date storeCloseStart, Date storeCloseEnd, Date createdAt, Date updatedAt) {
        this.id = id;
        this.businessStartTime = businessStartTime;
        this.businessEndTime = businessEndTime;
        this.freeExpressAmount = freeExpressAmount;
        this.storeCloseStart = storeCloseStart;
        this.storeCloseEnd = storeCloseEnd;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIG
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Config() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.ID
     *
     * @return the value of CONFIG.ID
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.ID
     *
     * @param id the value for CONFIG.ID
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.BUSINESS_START_TIME
     *
     * @return the value of CONFIG.BUSINESS_START_TIME
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Date getBusinessStartTime() {
        return businessStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.BUSINESS_START_TIME
     *
     * @param businessStartTime the value for CONFIG.BUSINESS_START_TIME
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public void setBusinessStartTime(Date businessStartTime) {
        this.businessStartTime = businessStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.BUSINESS_END_TIME
     *
     * @return the value of CONFIG.BUSINESS_END_TIME
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Date getBusinessEndTime() {
        return businessEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.BUSINESS_END_TIME
     *
     * @param businessEndTime the value for CONFIG.BUSINESS_END_TIME
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public void setBusinessEndTime(Date businessEndTime) {
        this.businessEndTime = businessEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @return the value of CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public BigDecimal getFreeExpressAmount() {
        return freeExpressAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @param freeExpressAmount the value for CONFIG.FREE_EXPRESS_AMOUNT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public void setFreeExpressAmount(BigDecimal freeExpressAmount) {
        this.freeExpressAmount = freeExpressAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.STORE_CLOSE_START
     *
     * @return the value of CONFIG.STORE_CLOSE_START
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Date getStoreCloseStart() {
        return storeCloseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.STORE_CLOSE_START
     *
     * @param storeCloseStart the value for CONFIG.STORE_CLOSE_START
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public void setStoreCloseStart(Date storeCloseStart) {
        this.storeCloseStart = storeCloseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.STORE_CLOSE_END
     *
     * @return the value of CONFIG.STORE_CLOSE_END
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Date getStoreCloseEnd() {
        return storeCloseEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.STORE_CLOSE_END
     *
     * @param storeCloseEnd the value for CONFIG.STORE_CLOSE_END
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public void setStoreCloseEnd(Date storeCloseEnd) {
        this.storeCloseEnd = storeCloseEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.CREATED_AT
     *
     * @return the value of CONFIG.CREATED_AT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.CREATED_AT
     *
     * @param createdAt the value for CONFIG.CREATED_AT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONFIG.UPDATED_AT
     *
     * @return the value of CONFIG.UPDATED_AT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONFIG.UPDATED_AT
     *
     * @param updatedAt the value for CONFIG.UPDATED_AT
     *
     * @mbg.generated Mon Sep 25 14:52:33 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}