package com.westee.cake.generate;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ID
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.NAME
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.CREATED_AT
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.UPDATED_AT
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROLE
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public Role(Long id, String name, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.name = name;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public Role() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ID
     *
     * @return the value of ROLE.ID
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ID
     *
     * @param id the value for ROLE.ID
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.NAME
     *
     * @return the value of ROLE.NAME
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.NAME
     *
     * @param name the value for ROLE.NAME
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.CREATED_AT
     *
     * @return the value of ROLE.CREATED_AT
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.CREATED_AT
     *
     * @param createdAt the value for ROLE.CREATED_AT
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.UPDATED_AT
     *
     * @return the value of ROLE.UPDATED_AT
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.UPDATED_AT
     *
     * @param updatedAt the value for ROLE.UPDATED_AT
     *
     * @mbg.generated Wed Dec 06 14:12:31 CST 2023
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}