package com.westee.cake.generate;

import java.io.Serializable;
import java.util.Date;

public class Roles implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLES.ID
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLES.NAME
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLES.CREATED_AT
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLES.UPDATED_AT
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROLES
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLES.ID
     *
     * @return the value of ROLES.ID
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLES.ID
     *
     * @param id the value for ROLES.ID
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLES.NAME
     *
     * @return the value of ROLES.NAME
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLES.NAME
     *
     * @param name the value for ROLES.NAME
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLES.CREATED_AT
     *
     * @return the value of ROLES.CREATED_AT
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLES.CREATED_AT
     *
     * @param createdAt the value for ROLES.CREATED_AT
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLES.UPDATED_AT
     *
     * @return the value of ROLES.UPDATED_AT
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLES.UPDATED_AT
     *
     * @param updatedAt the value for ROLES.UPDATED_AT
     *
     * @mbg.generated Tue May 09 10:08:12 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}