package com.westee.cake.entity;

import com.westee.cake.generate.Goods;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class GoodsWithImages extends Goods {
    List<String> images;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @param id
     * @param categoryId
     * @param name
     * @param description
     * @param imgUrl
     * @param price
     * @param vipPrice
     * @param shopId
     * @param stock
     * @param status
     * @param createdAt
     * @param updatedAt
     * @param weight
     * @param goodsType
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public GoodsWithImages(Long id, Long categoryId, String name, String description, String imgUrl, BigDecimal price,
                           BigDecimal vipPrice, Long shopId, Integer stock, String status, Date createdAt,
                           Date updatedAt, Integer weight, Integer goodsType, List<String> images) {
        super(id, categoryId, name, description, imgUrl, price, vipPrice, shopId, stock, status, createdAt, updatedAt, weight, goodsType);
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @param id
     * @param categoryId
     * @param name
     * @param description
     * @param imgUrl
     * @param price
     * @param vipPrice
     * @param shopId
     * @param stock
     * @param status
     * @param createdAt
     * @param updatedAt
     * @param weight
     * @param goodsType
     * @param details
     * @mbg.generated Thu Sep 21 23:10:18 CST 2023
     */
    public GoodsWithImages(Long id, Long categoryId, String name, String description, String imgUrl, BigDecimal price,
                           BigDecimal vipPrice, Long shopId, Integer stock, String status, Date createdAt,
                           Date updatedAt, Integer weight, Integer goodsType, String details, List<String> images) {
        super(id, categoryId, name, description, imgUrl, price, vipPrice, shopId, stock, status, createdAt, updatedAt, weight, goodsType, details);
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Thu May 25 17:00:36 CST 2023
     */
    public GoodsWithImages() {
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }
}
