package com.westee.cake.entity;

import com.westee.cake.generate.Goods;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class GoodsWithImages extends Goods {
    List<String> images;

    public GoodsWithImages(Long id, Long categoryId, String name, String description, String imgUrl, BigDecimal price,
                           BigDecimal vipPrice, Integer stock, String status, Date createdAt, Date updatedAt,
                           Long shopId, String details, List<String> images) {
        super(id, categoryId, name, description, imgUrl, price, vipPrice, stock, status, createdAt, updatedAt, shopId, details);
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Thu May 25 17:00:36 CST 2023
     */
    public GoodsWithImages() {
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }
}
