CREATE TABLE `ORDER_TABLE`
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT,
    TOTAL_PRICE     BIGINT,      -- 价格，单位分
    ADDRESS_ID      BIGINT,
    EXPRESS_COMPANY VARCHAR(16),
    EXPRESS_ID      VARCHAR(128),
    STATUS          VARCHAR(16), -- PENDING 待付款 PAID 已付款 DELIVERED 物流中 RECEIVED 已收货
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_ORDER_ADDRESS
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES ADDRESS (ID)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `ORDER_GOODS`
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    GOODS_ID BIGINT,
    ORDER_ID BIGINT,
    NUMBER   BIGINT -- 单位 分
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
