ALTER TABLE CHARGE MODIFY AMOUNT DECIMAL(12, 2);
ALTER TABLE CHARGE MODIFY PRESENT DECIMAL(12, 2);
ALTER TABLE CHARGE_OPTION MODIFY AMOUNT DECIMAL(12, 2);
ALTER TABLE CHARGE_OPTION MODIFY GIFT DECIMAL(12, 2);


