CREATE TABLE CHARGE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID     BIGINT,
    CHARGE_TYPE VARCHAR(10),
    AMOUNT      DECIMAL,
    REMARK      VARCHAR(200),
    STATUS      VARCHAR(10), -- fail ok
    PRESENT     DECIMAL,    -- 赠送金额
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT NOW()
);
ALTER TABLE USER
    ADD BALANCE BIGINT;