CREATE TABLE COUPON
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME            VARCHAR(255)   NOT NULL,
    DESCRIPTION     TEXT,
    DISCOUNT_TYPE   ENUM('AMOUNT', 'PERCENTAGE') NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10, 2) NOT NULL,
    MINIMUM_AMOUNT  DECIMAL(10, 2),
    START_DATE      TIMESTAMP               DEFAULT NOW() NOT NULL,
    END_DATE        TIMESTAMP               DEFAULT NOW() NOT NULL,
    CREATED_AT      TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE TABLE USER_COUPON
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT       NOT NULL,
    COUPON_ID  BIGINT       NOT NULL,
    USED       TINYINT(1) NOT NULL DEFAULT 0, -- 0 未使用 1 已使用
    USED_TIME  TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    FOREIGN KEY (COUPON_ID) REFERENCES COUPON (ID),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);