CREATE TABLE CHARGE_OPTION
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(20),
    AMOUNT     DECIMAL,
    GIFT       DECIMAL, -- 赠送金额
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);